const ROLE = {
  ADMIN_ROLE: 1,
  CLUB_ROLE: 2,
  CRICKET_PLAYER_ROLE: 3,
  FOOTBALL_PLAYER_ROLE: 4,
  PATIENT_ROLE: 0,
  HOMEOPATHY_DOCTOR_ROLE: 2,
  ALLOPATH_DOCTOR_ROLE: 3,
  AYURVEDIC_DOCTOR_ROLE:4,
  HOSPITAL_ROLE: 4,
}

export default ROLE;